version: '3'

services:
  tomcat: 
    build: ./docker/tomcat/
    ports: 
      - "8888:8080"
  
  fuseki:
    build: ./docker/fuseki/
    ports:
      - "8383:3030"
    environment:
      - ADMIN_PASSWORD=pw123
    command: ["/jena-fuseki/fuseki-server", "--file", "1_MiCorr_v2_RDF_NEW.owl", "/MiCorrDS"] 
