version: '3'

services:
  tomcat: 
    build: ./docker/tomcat/
    ports: 
      - "8888:8080"
  
  fuseki:
    image: stain/jena-fuseki
    volumes:
      - ./docker/fuseki:/jena-fuseki/graph
    ports:
      - "8383:3030"
    environment:
      - ADMIN_PASSWORD=pw123

